# -*- coding: utf-8 -*-
"""Fiture Extraction in Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o8N5whVC39HUl_1aQLCs9y0kCARU8q9

# 1. Word Embedding
"""

# Import model
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk

# Download Punkt tokenizer from nltk
nltk.download('punkt')
nltk.download('punkt_tab')

text_data = [
    'Saya suka makan bakso',
    'Bakso enak dan lezat',
    'Makanan favorit saya adalah nasi goreng',
    'Nasi goreng pedas adalah makanan favorit saya',
    'Saya suka makanan manis seperti es krim',
]

tokenized_data = [word_tokenize(sentence.lower()) for sentence in text_data]

model = Word2Vec(sentences=tokenized_data, vector_size=100, window=5, min_count=1, workers=4)

word_vectors = model.wv

similar_words = word_vectors.most_similar('bakso', topn=3)
print("Kata-kata yang mirip dengan 'bakso':", similar_words)

vector = word_vectors['bakso']
print("Vektor untuk 'bakso':", vector)

"""# 2. Bag of Words (BoW)"""

from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "Ini adalah contoh dokumen pertama.",
    "Ini adalah dokumen kedua.",
    "Ini adalah dokumen ketiga.",
    "Ini adalah contoh contoh contoh."
]

vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(documents)

bow_matrix.toarray()

features = vectorizer.get_feature_names_out()

print("Matriks BoW:")
print(bow_matrix.toarray())

print("\nDaftar Fitur:")
print(features)

"""# 3. N-gram"""

from nltk.util import ngrams

sentences = [
    "Saya suka makan bakso enak di warung dekat rumah.",
    "Nasi goreng adalah salah satu makanan favorit saya.",
    "Es krim coklat sangat lezat dan menyegarkan.",
    "Saat hari hujan, saya suka minum teh hangat.",
    "Pemandangan pegunungan di pagi hari sangat indah.",
    "Bola basket adalah olahraga favorit saya sejak kecil."
]

for sentence in sentences:
  words = sentence.split()
  unigrams = list(ngrams(words, 1))
  bigrams = list(ngrams(words, 2))
  trigrams = list(ngrams(words, 3))

print("\nKalimat:", sentence)
print("1-gram:")
for gram in unigrams:
    print(gram)
print("\n2-gram:")
for gram in bigrams:
    print(gram)
print("\n3-gram:")
for gram in trigrams:
    print(gram)